// Package flashduty implements FlashDuty MCP tools and API helpers.
package flashduty

import (
	"github.com/mark3labs/mcp-go/mcp"

	"github.com/futuretea/flashduty-mcp-server/pkg/toolset"
)

// Toolset provides FlashDuty incident management tools.
type Toolset struct {
	// ReadOnly disables write operations (create, ack, resolve, reopen, snooze, comment, close, update, assign)
	ReadOnly bool
}

var (
	itemsInteger = map[string]any{"type": "integer"}
	itemsString  = map[string]any{"type": "string"}
)

// GetName returns the FlashDuty toolset name.
func (t *Toolset) GetName() string {
	return "flashduty"
}

// GetDescription returns a human-readable FlashDuty toolset description.
func (t *Toolset) GetDescription() string {
	return "FlashDuty incident management and alert tools"
}

// GetTools builds the tool list, omitting write tools when ReadOnly is set.
func (t *Toolset) GetTools(_ any) []toolset.ServerTool {
	tools := []toolset.ServerTool{
		// ===== Incident Tools =====
		{
			Tool: mcp.NewTool("list_incidents",
				mcp.WithDescription("List incidents from FlashDuty. Specify time_range (e.g., '24h', '7d') or start_time+end_time (unix seconds). Use brief=true to reduce response size (recommended for initial queries)."),
				mcp.WithString("time_range",
					mcp.Description("Relative time range: duration '1h', '24h', '7d', '30d', '1w', '6M', or named range 'last_day', 'last_week', 'week_before_last'. Alternative to start_time+end_time."),
				),
				mcp.WithNumber("start_time",
					mcp.Description("Search interval start time in unix seconds. Required if time_range is not set."),
				),
				mcp.WithNumber("end_time",
					mcp.Description("Search interval end time in unix seconds. Required if time_range is not set."),
				),
				mcp.WithBoolean("brief",
					mcp.Description("If true, return only key fields (incident_id, title, incident_severity, progress, created_at, channel_name, channel_id, num) to reduce data volume. Recommended for listing."),
				),
				mcp.WithString("progress",
					mcp.Description("Filter by progress status. Options: 'Triggered', 'Processing', 'Closed', or comma-separated combination like 'Triggered,Processing'."),
				),
				mcp.WithString("incident_severity",
					mcp.Description("Filter by severity. Options: 'Critical', 'Warning', 'Info', or comma-separated combination."),
				),
				mcp.WithString("title",
					mcp.Description("Filter by incident title. Exact match by default, wrap with '/' for regex, use '*' or '?' for wildcards."),
				),
				mcp.WithArray("channel_ids",
					mcp.Description("Filter by collaboration space IDs."),
					mcp.Items(itemsInteger),
				),
				mcp.WithArray("responder_ids",
					mcp.Description("Filter by responder (assignee) person IDs."),
					mcp.Items(itemsInteger),
				),
				mcp.WithArray("acker_ids",
					mcp.Description("Filter by acknowledger person IDs."),
					mcp.Items(itemsInteger),
				),
				mcp.WithArray("creator_ids",
					mcp.Description("Filter by creator person IDs. 0 means system-generated."),
					mcp.Items(itemsInteger),
				),
				mcp.WithObject("labels",
					mcp.Description("Filter by labels. Object with label key -> array of values. Supports exact, regex (/pattern/), and wildcard (*,?) matching."),
				),
				mcp.WithNumber("limit",
					mcp.Description("Page size (1-100, default 20)."),
				),
				mcp.WithNumber("p",
					mcp.Description("Page number starting from 1."),
				),
			),
			Handler: handleListIncidents,
		},
		{
			Tool: mcp.NewTool("get_incident",
				mcp.WithDescription("Get detailed information about a specific incident by its ID."),
				mcp.WithString("incident_id",
					mcp.Required(),
					mcp.Description("The incident ID (ObjectID type)."),
				),
			),
			Handler: handleGetIncident,
		},

		// ===== Alert Tools =====
		{
			Tool: mcp.NewTool("list_alerts",
				mcp.WithDescription("List alerts from FlashDuty. Specify time_range (e.g., '24h', '7d') or start_time+end_time (unix seconds). Use brief=true to reduce response size."),
				mcp.WithString("time_range",
					mcp.Description("Relative time range: duration '1h', '24h', '7d', '30d', '1w', '6M', or named range 'last_day', 'last_week', 'week_before_last'. Alternative to start_time+end_time."),
				),
				mcp.WithNumber("start_time",
					mcp.Description("Search interval start time in unix seconds. Required if time_range is not set."),
				),
				mcp.WithNumber("end_time",
					mcp.Description("Search interval end time in unix seconds. Required if time_range is not set."),
				),
				mcp.WithBoolean("brief",
					mcp.Description("If true, return only key fields (alert_id, title, alert_severity, is_active, created_at, channel_name, channel_id) to reduce data volume."),
				),
				mcp.WithString("alert_severity",
					mcp.Description("Filter by severity. Options: 'Critical', 'Warning', 'Info', or comma-separated combination."),
				),
				mcp.WithString("title",
					mcp.Description("Filter by alert title. Supports exact match, regex (wrap with '/'), and wildcards ('*', '?')."),
				),
				mcp.WithBoolean("is_active",
					mcp.Description("Filter by active status. true=active only, false=recovered only, omit=all."),
				),
				mcp.WithArray("channel_ids",
					mcp.Description("Filter by collaboration space IDs."),
					mcp.Items(itemsInteger),
				),
				mcp.WithObject("labels",
					mcp.Description("Filter by labels. Object with label key -> array of values. Supports exact, regex (/pattern/), and wildcard (*,?) matching."),
				),
				mcp.WithNumber("limit",
					mcp.Description("Page size (1-100, default 20)."),
				),
				mcp.WithNumber("p",
					mcp.Description("Page number starting from 1."),
				),
			),
			Handler: handleListAlerts,
		},
		{
			Tool: mcp.NewTool("get_alert",
				mcp.WithDescription("Get detailed information about a specific alert by its ID."),
				mcp.WithString("alert_id",
					mcp.Required(),
					mcp.Description("The alert ID."),
				),
			),
			Handler: handleGetAlert,
		},

		// ===== Channel (Collaboration Space) Tools =====
		{
			Tool: mcp.NewTool("list_channels",
				mcp.WithDescription("List collaboration spaces (channels) from FlashDuty."),
				mcp.WithString("query",
					mcp.Description("Search keyword to match channel name and description."),
				),
				mcp.WithNumber("limit",
					mcp.Description("Page size."),
				),
				mcp.WithNumber("p",
					mcp.Description("Page number starting from 1."),
				),
			),
			Handler: handleListChannels,
		},
		{
			Tool: mcp.NewTool("get_channel",
				mcp.WithDescription("Get detailed information about a specific collaboration space (channel) by its ID."),
				mcp.WithNumber("channel_id",
					mcp.Required(),
					mcp.Description("The channel ID."),
				),
			),
			Handler: handleGetChannel,
		},

		// ===== Team Tools =====
		{
			Tool: mcp.NewTool("list_teams",
				mcp.WithDescription("List teams from FlashDuty."),
				mcp.WithString("query",
					mcp.Description("Search keyword to match team name and description."),
				),
				mcp.WithNumber("limit",
					mcp.Description("Page size."),
				),
				mcp.WithNumber("p",
					mcp.Description("Page number starting from 1."),
				),
			),
			Handler: handleListTeams,
		},

		// ===== Member Tools =====
		{
			Tool: mcp.NewTool("list_members",
				mcp.WithDescription("List members from FlashDuty."),
				mcp.WithString("query",
					mcp.Description("Search keyword to match member name and email. If recognized as phone number, will match phone strictly."),
				),
				mcp.WithNumber("limit",
					mcp.Description("Page size."),
				),
				mcp.WithNumber("p",
					mcp.Description("Page number starting from 1."),
				),
			),
			Handler: handleListMembers,
		},

		// ===== Insight Tools =====
		{
			Tool: mcp.NewTool("get_incident_stats",
				mcp.WithDescription("Get aggregated incident statistics from FlashDuty. Returns counts, MTTA, MTTR, ack rate, noise reduction, etc. Specify time_range (e.g., '7d', '30d') or start_time+end_time (unix seconds). Use aggregate_unit to break down by time period."),
				mcp.WithString("time_range",
					mcp.Description("Relative time range: duration '1h', '24h', '7d', '30d', '1w', '6M', or named range 'last_day', 'last_week', 'week_before_last'. Alternative to start_time+end_time."),
				),
				mcp.WithNumber("start_time",
					mcp.Description("Start time in unix seconds. Required if time_range is not set."),
				),
				mcp.WithNumber("end_time",
					mcp.Description("End time in unix seconds. Max span 6 months. Required if time_range is not set."),
				),
				mcp.WithArray("channel_ids",
					mcp.Description("Filter by collaboration space IDs."),
					mcp.Items(itemsInteger),
				),
				mcp.WithArray("team_ids",
					mcp.Description("Filter by team IDs."),
					mcp.Items(itemsInteger),
				),
				mcp.WithArray("severities",
					mcp.Description("Filter by severities. Options: 'Critical', 'Warning', 'Info'."),
					mcp.Items(itemsString),
				),
				mcp.WithString("aggregate_unit",
					mcp.Description("Time aggregation unit: 'day', 'week', or 'month'. If omitted, aggregates the entire period."),
				),
				mcp.WithString("query",
					mcp.Description("Filter by incident title (fuzzy match)."),
				),
				mcp.WithObject("labels",
					mcp.Description("Filter by labels as key-value pairs (exact match)."),
				),
			),
			Handler: handleGetIncidentStats,
		},

		// ===== Incident Timeline =====
		{
			Tool: mcp.NewTool("get_incident_timeline",
				mcp.WithDescription("Get the timeline (feed) of an incident, including comments, acks, resolves, escalations, notifications, etc."),
				mcp.WithString("incident_id",
					mcp.Required(),
					mcp.Description("The incident ID."),
				),
				mcp.WithArray("types",
					mcp.Description("Filter by event types. Options include: 'i_comm' (comment), 'i_notify', 'i_new', 'i_assign', 'i_ack', 'i_rslv', 'i_reopen', 'i_snooze', 'i_merge', 'i_r_severity', etc."),
					mcp.Items(itemsString),
				),
				mcp.WithNumber("limit",
					mcp.Description("Page size."),
				),
				mcp.WithNumber("p",
					mcp.Description("Page number starting from 1."),
				),
			),
			Handler: handleGetIncidentTimeline,
		},

		// ===== Incident-Alert Association =====
		{
			Tool: mcp.NewTool("list_incident_alerts",
				mcp.WithDescription("List alerts associated with a specific incident."),
				mcp.WithString("incident_id",
					mcp.Required(),
					mcp.Description("The incident ID."),
				),
				mcp.WithBoolean("is_active",
					mcp.Description("Filter by active status. true=active only, false=recovered only, omit=all."),
				),
				mcp.WithNumber("limit",
					mcp.Description("Page size (max 1000, default 1000)."),
				),
				mcp.WithNumber("p",
					mcp.Description("Page number starting from 1."),
				),
			),
			Handler: handleListIncidentAlerts,
		},

		// ===== Schedule (On-call) Tools =====
		{
			Tool: mcp.NewTool("list_schedules",
				mcp.WithDescription("List on-call schedules from FlashDuty."),
				mcp.WithArray("team_ids",
					mcp.Required(),
					mcp.Description("List of team IDs to filter schedules."),
					mcp.Items(itemsInteger),
				),
				mcp.WithString("query",
					mcp.Description("Search keyword to match schedule name."),
				),
				mcp.WithNumber("limit",
					mcp.Description("Page size."),
				),
				mcp.WithNumber("p",
					mcp.Description("Page number starting from 1."),
				),
			),
			Handler: handleListSchedules,
		},

		// ===== Similar Incidents =====
		{
			Tool: mcp.NewTool("list_similar_incidents",
				mcp.WithDescription("Find similar historical incidents for a given incident. Useful for pattern analysis and diagnosis."),
				mcp.WithString("incident_id",
					mcp.Required(),
					mcp.Description("The incident ID to find similar incidents for."),
				),
				mcp.WithNumber("limit",
					mcp.Description("Maximum number of similar incidents to return (max 20)."),
				),
			),
			Handler: handleListSimilarIncidents,
		},

		// ===== Change Tools =====
		{
			Tool: mcp.NewTool("query_changes",
				mcp.WithDescription("Query deployment/change events from FlashDuty. Useful for correlating incidents with recent deployments. Time range is optional."),
				mcp.WithString("time_range",
					mcp.Description("Relative time range: '1h', '24h', '7d', '30d', '1w', '6M', or 'last_day', 'last_week', 'week_before_last'. Alternative to start_time+end_time."),
				),
				mcp.WithNumber("start_time",
					mcp.Description("Start time in unix seconds."),
				),
				mcp.WithNumber("end_time",
					mcp.Description("End time in unix seconds."),
				),
				mcp.WithString("query",
					mcp.Description("Search keyword to filter changes."),
				),
				mcp.WithArray("channel_ids",
					mcp.Description("Filter by collaboration space IDs."),
					mcp.Items(itemsInteger),
				),
				mcp.WithArray("integration_ids",
					mcp.Description("Filter by integration IDs."),
					mcp.Items(itemsInteger),
				),
				mcp.WithString("order_by",
					mcp.Description("Field to order by (e.g., 'start_time')."),
				),
				mcp.WithBoolean("asc",
					mcp.Description("Sort ascending if true, descending if false."),
				),
				mcp.WithBoolean("include_events",
					mcp.Description("Include change events in the response."),
				),
				mcp.WithNumber("limit",
					mcp.Description("Page size (1-100, default 20)."),
				),
				mcp.WithNumber("p",
					mcp.Description("Page number starting from 1."),
				),
			),
			Handler: handleQueryChanges,
		},

		// ===== Escalation Rules =====
		{
			Tool: mcp.NewTool("query_escalation_rules",
				mcp.WithDescription("Query escalation rules for a collaboration space. Returns the escalation policy configuration."),
				mcp.WithNumber("channel_id",
					mcp.Required(),
					mcp.Description("The collaboration space (channel) ID."),
				),
			),
			Handler: handleQueryEscalationRules,
		},

		// ===== Custom Fields =====
		{
			Tool: mcp.NewTool("query_fields",
				mcp.WithDescription("Query custom field definitions from FlashDuty. Returns all configured custom fields for incidents."),
			),
			Handler: handleQueryFields,
		},

		// ===== Incident Aggregation =====
		{
			Tool: mcp.NewTool("aggregate_incidents",
				mcp.WithDescription("Aggregate and group incidents by one or more dimensions (e.g., severity, channel, progress, or labels.xxx). Automatically fetches all matching incidents (up to max_incidents) and returns grouped counts with optional per-group details. Useful for incident distribution analysis, SLA reporting, and trend investigation. Specify time_range (e.g., '24h', '7d') or start_time+end_time."),
				mcp.WithString("time_range",
					mcp.Description("Relative time range: duration '1h', '24h', '7d', '30d', '1w', '6M', or named range 'last_day', 'last_week', 'week_before_last'. Alternative to start_time+end_time."),
				),
				mcp.WithNumber("start_time",
					mcp.Description("Search interval start time in unix seconds. Required if time_range is not set."),
				),
				mcp.WithNumber("end_time",
					mcp.Description("Search interval end time in unix seconds. Required if time_range is not set."),
				),
				mcp.WithArray("group_by",
					mcp.Required(),
					mcp.Description("Dimensions to group by. Built-in: 'severity'/'incident_severity', 'channel', 'progress'. Custom labels: 'labels.<key>' (e.g., 'labels.env', 'labels.service'). Multiple dimensions create composite groups."),
					mcp.Items(itemsString),
				),
				mcp.WithNumber("channel_id",
					mcp.Description("Filter by collaboration space ID. Alternative to channel_name."),
				),
				mcp.WithString("channel_name",
					mcp.Description("Filter by collaboration space name (fuzzy match, resolved to channel_id automatically). Alternative to channel_id."),
				),
				mcp.WithArray("severities",
					mcp.Description("Filter by severities. Options: 'Critical', 'Warning', 'Info'."),
					mcp.Items(itemsString),
				),
				mcp.WithString("query",
					mcp.Description("Filter by incident title (fuzzy match)."),
				),
				mcp.WithBoolean("include_details",
					mcp.Description("If true, include per-incident detail records inside each group. Defaults to false."),
				),
				mcp.WithArray("detail_fields",
					mcp.Description("Fields to include in each detail record when include_details=true. Defaults to: incident_id, title, incident_severity, progress, created_at, channel_name, channel_id."),
					mcp.Items(itemsString),
				),
				mcp.WithNumber("max_incidents",
					mcp.Description("Maximum number of incidents to fetch across all pages (default 500). Increase for larger datasets, but be aware of performance impact."),
				),
			),
			Handler: handleAggregateIncidents,
		},
	}

	// Write tools - only enabled when not in read-only mode
	if !t.ReadOnly {
		tools = append(tools,
			// ===== Incident Write Tools =====
			toolset.ServerTool{
				Tool: mcp.NewTool("create_incident",
					mcp.WithDescription("Create a new incident in FlashDuty."),
					mcp.WithString("title",
						mcp.Required(),
						mcp.Description("Incident title."),
					),
					mcp.WithString("incident_severity",
						mcp.Required(),
						mcp.Description("Severity level. Must be one of: 'Critical', 'Warning', 'Info'."),
					),
					mcp.WithString("description",
						mcp.Description("Incident description. Can be plain text or markdown."),
					),
					mcp.WithNumber("channel_id",
						mcp.Description("Collaboration space ID to associate the incident with."),
					),
				),
				Handler: handleCreateIncident,
			},
			toolset.ServerTool{
				Tool: mcp.NewTool("ack_incidents",
					mcp.WithDescription("Acknowledge (claim) one or more incidents."),
					mcp.WithArray("incident_ids",
						mcp.Required(),
						mcp.Description("List of incident IDs to acknowledge."),
						mcp.Items(itemsString),
					),
				),
				Handler: handleAckIncidents,
			},
			toolset.ServerTool{
				Tool: mcp.NewTool("resolve_incidents",
					mcp.WithDescription("Resolve (close) one or more incidents. Optionally provide root cause and resolution."),
					mcp.WithArray("incident_ids",
						mcp.Required(),
						mcp.Description("List of incident IDs to resolve."),
						mcp.Items(itemsString),
					),
					mcp.WithString("root_cause",
						mcp.Description("Root cause of the incident."),
					),
					mcp.WithString("resolution",
						mcp.Description("How the incident was resolved."),
					),
				),
				Handler: handleResolveIncidents,
			},
			toolset.ServerTool{
				Tool: mcp.NewTool("reopen_incidents",
					mcp.WithDescription("Reopen one or more previously resolved incidents."),
					mcp.WithArray("incident_ids",
						mcp.Required(),
						mcp.Description("List of incident IDs to reopen."),
						mcp.Items(itemsString),
					),
					mcp.WithString("reason",
						mcp.Required(),
						mcp.Description("Reason for reopening the incident."),
					),
				),
				Handler: handleReopenIncidents,
			},
			toolset.ServerTool{
				Tool: mcp.NewTool("snooze_incidents",
					mcp.WithDescription("Snooze (temporarily mute) one or more incidents for a specified number of minutes."),
					mcp.WithArray("incident_ids",
						mcp.Required(),
						mcp.Description("List of incident IDs to snooze."),
						mcp.Items(itemsString),
					),
					mcp.WithNumber("minutes",
						mcp.Required(),
						mcp.Description("Number of minutes to snooze (1-1440)."),
					),
				),
				Handler: handleSnoozeIncidents,
			},
			toolset.ServerTool{
				Tool: mcp.NewTool("comment_incidents",
					mcp.WithDescription("Add a comment to one or more incidents."),
					mcp.WithArray("incident_ids",
						mcp.Required(),
						mcp.Description("List of incident IDs to comment on."),
						mcp.Items(itemsString),
					),
					mcp.WithString("comment",
						mcp.Required(),
						mcp.Description("Comment content (1-500 characters)."),
					),
				),
				Handler: handleCommentIncidents,
			},
			// ===== Alert Write Tools =====
			toolset.ServerTool{
				Tool: mcp.NewTool("close_alerts",
					mcp.WithDescription("Close one or more alerts."),
					mcp.WithArray("alert_ids",
						mcp.Required(),
						mcp.Description("List of alert IDs to close."),
						mcp.Items(itemsString),
					),
				),
				Handler: handleCloseAlerts,
			},
			// ===== Incident Update Tools =====
			toolset.ServerTool{
				Tool: mcp.NewTool("update_incident",
					mcp.WithDescription("Update an incident's details. Can modify title, description, severity, impact, root cause, and resolution. At least one field besides incident_id must be provided."),
					mcp.WithString("incident_id",
						mcp.Required(),
						mcp.Description("The incident ID to update."),
					),
					mcp.WithString("title",
						mcp.Description("New incident title."),
					),
					mcp.WithString("description",
						mcp.Description("New incident description. Supports markdown."),
					),
					mcp.WithString("incident_severity",
						mcp.Description("New severity level. Must be one of: 'Critical', 'Warning', 'Info'."),
					),
					mcp.WithString("impact",
						mcp.Description("Impact description of the incident."),
					),
					mcp.WithString("root_cause",
						mcp.Description("Root cause of the incident."),
					),
					mcp.WithString("resolution",
						mcp.Description("Resolution description of the incident."),
					),
				),
				Handler: handleUpdateIncident,
			},
			// ===== Incident Assignment Tools =====
			toolset.ServerTool{
				Tool: mcp.NewTool("assign_incident",
					mcp.WithDescription("Assign one or more incidents to specific persons or an escalation rule."),
					mcp.WithArray("incident_ids",
						mcp.Required(),
						mcp.Description("List of incident IDs to assign."),
						mcp.Items(itemsString),
					),
					mcp.WithString("type",
						mcp.Description("Assignment type: 'assign' for direct person assignment, 'escalateRule' for escalation rule. Default: 'assign'."),
					),
					mcp.WithArray("person_ids",
						mcp.Description("List of person IDs to assign to (when type is 'assign')."),
						mcp.Items(itemsInteger),
					),
					mcp.WithNumber("escalate_rule_id",
						mcp.Description("Escalation rule ID to assign to (when type is 'escalateRule')."),
					),
				),
				Handler: handleAssignIncident,
			},
		)
	}

	return tools
}
